language: node_js
sudo: false
node_js:
  - 10
install:
  - cd api-gateway-microservice && npm install
cache:
  directories:
    - "node_modules"

services:
  - docker

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=akshayrajvanshi1992/api-gateway-microservice
  - export TAG=`if [ "$TRAVIS_BRANCH" == "api-gateway-microservice" ]; then echo $TRAVIS_COMMIT; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t api-gateway-microservice .
  - docker tag api-gateway-microservice $REPO:$TAG
  - docker push $REPO:$TAG
  - docker tag api-gateway-microservice $REPO:latest
  - docker push $REPO:latest
  - curl -u admin:admin "http://149.165.171.113:8080/job/Update-deployment/buildWithParameters?token=admin&TAG=$TAG&service=api-gateway"
