language: java
jdk: oraclejdk13
sudo: false
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::6}
services:
  - docker

script:
  - cd DataLinkRetrieve
  - mvn -Dmaven.test.skip test-compile jar:test-jar install

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=akshayrajvanshi1992/data-retrieval-microservice
  — echo $REPO:$TAG:$COMMIT
  - docker build -t data-retrieval-microservice .
  - docker tag data-retrieval-microservice $REPO:$TRAVIS_BUILD_NUMBER
  - docker push $REPO:$TAG:$TRAVIS_BUILD_NUMBER