language: java
jdk: oraclejdk13
sudo: false
cache:
  directories:
    - $HOME/.m2

services:
  - docker

script:
  - cd DataLinkRetrieve
  - mvn -Dmaven.test.skip test-compile jar:test-jar install

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=akshayrajvanshi1992/data-retrieval-microservice
  - export TAG=`if [ "$TRAVIS_BRANCH" == "data-link-retrieval-microservice" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t data-retrieval-microservice .
  - docker tag data-retrieval-microservice $REPO:$TAG
  - docker push $REPO:$TAG