---
kind: Service
apiVersion: v1
metadata:
  name: dataretrievalservice
spec:
  selector:
    app: user-management
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
    #   # Port to forward to inside the pod
    #   targetPort: 4000
    #   # Port accessible outside cluster
    #   nodePort: 30001
  # type: LoadBalancer

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: data-retrieval-deployment
spec:
  selector:
    matchLabels:
      app: data-retrieval
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: data-retrieval
    spec:
      containers:
        - name: data-retrieval
          image: akshayrajvanshi1992/data-retrieval-microservice:data-link-retrieve-microservice
          # ports:
          # - containerPort: 4000
