---
kind: Service
apiVersion: v1
metadata:
  name: sessionmanagementservice
spec:
  selector:
    app: session-management
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 3003

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: session-management-deployment
spec:
  selector:
    matchLabels:
      app: session-management
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: session-management
    spec:
      containers:
        - name: session-management
          image: akshayrajvanshi1992/session-management-microservice:latest