---
kind: Service
apiVersion: v1
metadata:
  name: modelexecutionservice
spec:
  selector:
    app: model-execution
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 3005

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: model-execution-deployment
spec:
  selector:
    matchLabels:
      app: model-execution
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: model-execution
    spec:
      containers:
        - name: model-execution
          image: akshayrajvanshi1992/model-execution-microservice:latest