---
kind: Service
apiVersion: v1
metadata:
  name: apigatewayservice
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 3001
      # Port to forward to inside the pod
      targetPort: 4000
      # Port accessible outside cluster
      nodePort: 30001
  type: LoadBalancer
 
 
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: akshayrajvanshi1992/api-gateway-microservice:latest
        ports:
        - containerPort: 4000